using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace KanonBot.Generators;

[Generator]
public class CommandRegistryGenerator : IIncrementalGenerator
{
    private const string ICommandFullName = "CommandSystem.ICommand";
    private const string TargetNamespace = "CommandSystem.Execution";
    private const string TargetClassName = "CommandRegistrar";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var commandClasses = context
            .SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) =>
                    node is ClassDeclarationSyntax cds
                    && !cds.Modifiers.Any(SyntaxKind.AbstractKeyword),
                transform: static (ctx, _) => GetCommandInfo(ctx)
            )
            .Where(static c => c is not null);

        var collectedCommands = commandClasses.Collect();

        context.RegisterSourceOutput(
            collectedCommands,
            static (spc, commands) =>
            {
                var source = GenerateSource(commands);
                spc.AddSource($"{TargetClassName}.g.cs", source);
            }
        );
    }

    private static CommandInfo? GetCommandInfo(GeneratorSyntaxContext ctx)
    {
        var classDecl = (ClassDeclarationSyntax)ctx.Node;
        var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

        if (symbol is null || symbol.IsAbstract || symbol.IsGenericType)
            return null;

        if (!ImplementsICommand(symbol))
            return null;

        if (!HasParameterlessConstructor(symbol))
            return null;

        return new CommandInfo
        {
            FullyQualifiedName = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
        };
    }

    private static bool ImplementsICommand(INamedTypeSymbol symbol)
    {
        return symbol.AllInterfaces.Any(static i => i.ToDisplayString() == ICommandFullName);
    }

    private static bool HasParameterlessConstructor(INamedTypeSymbol symbol)
    {
        var constructors = symbol.InstanceConstructors;
        if (constructors.Length == 0)
            return true;

        return constructors.Any(
            static c => c.Parameters.Length == 0 && c.DeclaredAccessibility == Accessibility.Public
        );
    }

    private static string GenerateSource(ImmutableArray<CommandInfo?> commands)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using CommandSystem;");
        sb.AppendLine("using CommandSystem.Definition;");
        sb.AppendLine();
        sb.AppendLine($"namespace {TargetNamespace};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {TargetClassName}");
        sb.AppendLine("{");
        sb.AppendLine("    public static CommandRegistry BuildRegistry()");
        sb.AppendLine("    {");
        sb.AppendLine("        var registry = new CommandRegistry();");

        foreach (
            var cmd in commands
                .Where(static c => c is not null)
                .OrderBy(static c => c!.Value.FullyQualifiedName)
        )
        {
            sb.AppendLine($"        registry.Register(new {cmd!.Value.FullyQualifiedName}());");
        }

        sb.AppendLine("        return registry;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private struct CommandInfo
    {
        public string FullyQualifiedName;
    }
}
