global using global::System;
global using global::System.Collections.Generic;
global using global::System.Linq;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using desu_life_Bot;
global using static desu_life_Bot.Utils;
global using LanguageExt;
global using static LanguageExt.Prelude;
global using Serilog;