using System.Text.Json.Nodes;
using System.Text.Json.Serialization;
using KanonBot.API.OSU;
using KanonBot.API.PPYSB;
using KanonBot.Drivers;

namespace KanonBot.Serializer;

// OSU Models
[JsonSerializable(typeof(API.OSU.Models.BeatmapList))]
[JsonSerializable(typeof(API.OSU.Models.Beatmap))]
[JsonSerializable(typeof(API.OSU.Models.BeatmapFailtimes))]
[JsonSerializable(typeof(API.OSU.Models.BeatmapAttributes))]
[JsonSerializable(typeof(API.OSU.Models.BeatmapSearchResult))]
[JsonSerializable(typeof(API.OSU.Models.Beatmapset))]
[JsonSerializable(typeof(API.OSU.Models.BeatmapAvailability))]
[JsonSerializable(typeof(API.OSU.Models.BeatmapCovers))]
[JsonSerializable(typeof(API.OSU.Models.BeatmapHype))]
[JsonSerializable(typeof(API.OSU.Models.NominationsSummary))]
[JsonSerializable(typeof(API.OSU.Models.UserExtended))]
[JsonSerializable(typeof(API.OSU.Models.User))]
[JsonSerializable(typeof(API.OSU.Models.Country))]
[JsonSerializable(typeof(API.OSU.Models.UserCover))]
[JsonSerializable(typeof(API.OSU.Models.Count))]
[JsonSerializable(typeof(API.OSU.Models.UserPage))]
[JsonSerializable(typeof(API.OSU.Models.UserHighestRank))]
[JsonSerializable(typeof(API.OSU.Models.RankHistory))]
[JsonSerializable(typeof(API.OSU.Models.UserStatisticsModes))]
[JsonSerializable(typeof(API.OSU.Models.UserStatistics))]
[JsonSerializable(typeof(API.OSU.Models.UserGradeCounts))]
[JsonSerializable(typeof(API.OSU.Models.UserGroup))]
[JsonSerializable(typeof(API.OSU.Models.UserLevel))]
[JsonSerializable(typeof(API.OSU.Models.MonthlyCount))]
[JsonSerializable(typeof(API.OSU.Models.UserRank))]
[JsonSerializable(typeof(API.OSU.Models.UserAchievement))]
[JsonSerializable(typeof(API.OSU.Models.UserBadge))]
[JsonSerializable(typeof(API.OSU.Models.UserAccountHistory))]
[JsonSerializable(typeof(API.OSU.Models.Mod))]
[JsonSerializable(typeof(API.OSU.Models.BeatmapScore))]
[JsonSerializable(typeof(API.OSU.Models.Score))]
[JsonSerializable(typeof(API.OSU.Models.ScoreStatistics))]
[JsonSerializable(typeof(API.OSU.Models.ScoreWeight))]
[JsonSerializable(typeof(API.OSU.Models.BeatmapScoreLazer))]
[JsonSerializable(typeof(API.OSU.Models.ScoreLazer))]
[JsonSerializable(typeof(API.OSU.Models.Match))]
[JsonSerializable(typeof(API.OSU.Models.CurrentUserAttributes))]
[JsonSerializable(typeof(API.OSU.Models.CurrentUserPin))]
[JsonSerializable(typeof(API.OSU.Models.ScoreStatisticsLazer))]
[JsonSerializable(typeof(API.OSU.Models.Medal))]
[JsonSerializable(typeof(API.OSU.Models.MedalCompact))]
[JsonSerializable(typeof(API.OSU.Models.ScoreV1))]
[JsonSerializable(typeof(API.OSU.Models.UserV1))]
[JsonSerializable(typeof(API.OSU.Models.PPlusData))]
// PPYSB Models
[JsonSerializable(typeof(API.PPYSB.Models.MapResponseV2))]
[JsonSerializable(typeof(API.PPYSB.Models.Beatmap), TypeInfoPropertyName = "PPYSBBeatmap")]
[JsonSerializable(typeof(API.PPYSB.Models.ApiResponse))]
[JsonSerializable(typeof(API.PPYSB.Models.ApiResponseV2))]
[JsonSerializable(typeof(API.PPYSB.Models.ScoreResponseV2))]
[JsonSerializable(typeof(API.PPYSB.Models.PlayerScoreResponse))]
[JsonSerializable(typeof(API.PPYSB.Models.ScoreResponse))]
[JsonSerializable(typeof(API.PPYSB.Models.Score), TypeInfoPropertyName = "PPYSBScore")]
[JsonSerializable(typeof(API.PPYSB.Models.ScoreUser))]
[JsonSerializable(typeof(API.PPYSB.Models.UserResponse))]
[JsonSerializable(typeof(API.PPYSB.Models.User), TypeInfoPropertyName = "PPYSBUser")]
[JsonSerializable(typeof(API.PPYSB.Models.UserInfo))]
[JsonSerializable(typeof(API.PPYSB.Models.UserStats))]
[JsonSerializable(typeof(API.PPYSB.Models.UserStat))]
// IAM Models
[JsonSerializable(typeof(API.IAM.SubmitVerificationRequest))]
[JsonSerializable(typeof(API.IAM.BindSessionRequest))]
[JsonSerializable(typeof(API.IAM.BindSessionResponse))]
[JsonSerializable(typeof(API.IAM.SubmitCodeResponse))]
[JsonSerializable(typeof(API.IAM.BoundUserLookupResponse))]
[JsonSerializable(typeof(API.IAM.PpysbBoundUsersLookupResponse))]
[JsonSerializable(typeof(API.IAM.UserBindingsResponse))]
[JsonSerializable(typeof(API.IAM.UserBindings))]
[JsonSerializable(typeof(API.IAM.IamErrorResponse))]
[JsonSerializable(typeof(API.IAM.OsuBindingsResponse))]
[JsonSerializable(typeof(API.IAM.PpySbBindingsResponse))]
// Kagami Models
[JsonSerializable(typeof(API.Kagami.KanonBotProfile))]
[JsonSerializable(typeof(API.Kagami.KanonBotSettings))]
[JsonSerializable(typeof(API.Kagami.InstalledBadge))]
[JsonSerializable(typeof(API.Kagami.InfoPanelV2CustomTheme))]
[JsonSerializable(typeof(API.Kagami.KanonImages))]
[JsonSerializable(typeof(API.Kagami.UserBadgeResponse))]
[JsonSerializable(typeof(API.Kagami.UserPermissionsResponse))]
// Common types
[JsonSerializable(typeof(JsonNode))]
[JsonSerializable(typeof(JsonObject))]
[JsonSerializable(typeof(JsonArray))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(string[]))]
internal partial class KanonBotJsonContext : JsonSerializerContext
{
}
